// 實驗總表 — 所有實驗（含未來規劃）
const ALL_EXPERIMENTS = [
  { id: 'C01', title: '看不見的爆發力：黑蛇招喚術與酸鹼火箭', cat: '化學', concept: '糖熱分解碳化、小蘇打加熱/加酸產二氧化碳', format: '分組實作', duration: 100 },
  { id: 'C02', title: '星際科學實驗室：深海熔岩燈與爆漿水怪蛋', cat: '化學', concept: '油水不互溶密度差異、海藻酸鈉交聯成膜', format: '個人實作', duration: 120 },
  { id: 'P01', title: '神奇的靜電：閃電魔法杯與不插電馬達', cat: '物理', concept: '摩擦起電、感應起電、庫倫力驅動', format: '個人實作', duration: 120 },
  { id: 'P02', title: '電流與熱能的交響曲：保麗龍寶劍與電流麵包', cat: '物理', concept: '電流熱效應、電阻與能量轉換', format: '雙軌交叉進行', duration: 120 },
  { id: 'P03', title: '風的掌控者：人造雲與轉轉飛天杯', cat: '物理', concept: '白努力定律、瑪格努斯效應', format: '個人實作', duration: 100 },
  { id: null, title: '特務密碼：火焰解碼術', cat: '化學', concept: '硝酸鉀熱分解、助燃性應用', format: '個人實作', duration: 110 },
  { id: null, title: '冰雪奇緣：魔法天氣瓶', cat: '化學', concept: '樟腦結晶、溫度與溶解度', format: '個人實作', duration: 120 },
  { id: null, title: '點水成冰：急凍世界', cat: '化學', concept: '醋酸鈉過飽和溶液、結晶熱釋放', format: '個人實作', duration: 110 },
  { id: null, title: '魔法煉金術：三色變色杯', cat: '化學', concept: '氧化還原反應、酸鹼指示劑變化', format: '分組點滴板操作', duration: 90 },
  { id: null, title: '黑蛇招喚術與燃術軌跡', cat: '化學', concept: '蔗糖熱分解碳化、小蘇打受熱產氣', format: '分組實作', duration: 100 },
  { id: null, title: '大象的泡泡浴', cat: '化學', concept: '催化劑與反應速率、放熱反應', format: '分組實作', duration: 90 },
  { id: null, title: '水分子破壞者', cat: '化學', concept: '電化學、正負極氣體製備', format: '分組實作', duration: 105 },
  { id: null, title: '煉金術士的點金術', cat: '化學', concept: '氧化還原與置換、結晶型態觀察', format: '分組實作', duration: 120 },
  { id: null, title: '魔幻紅綠燈變色瓶', cat: '化學', concept: '葡萄糖氧化還原、亞甲基藍/靛胭脂', format: '個人實作', duration: 90 },
  { id: null, title: '夜光魔法與終極焰色', cat: '化學', concept: '原子光譜電子躍遷、化學發光冷光現象', format: '分組實作', duration: 100 },
  { id: null, title: '黑色磁力怪獸製造機', cat: '化學', concept: '高分子交聯作用、磁性物質感應', format: '個人實作', duration: 100 },
  { id: null, title: '尋找解藥：煉金術士矩陣', cat: '化學', concept: '離子沉澱反應、溶解度規則表格', format: '2人一組/點滴板', duration: 120 },
  { id: null, title: '時間規律者：自製時鐘', cat: '物理', concept: '古典力學、單擺等時性探究', format: '分組實作', duration: 90 },
  { id: null, title: '手動小吊車：帕斯卡契約', cat: '物理', concept: '簡單機械、槓桿原理與輪軸', format: '個人結構組裝', duration: 100 },
  { id: null, title: '天際探險：人造火箭', cat: '化學', concept: '氣體產氣壓、反作用力', format: '分組實作', duration: 90 },
];

// 器材採購清單
const MATERIALS_LIST = [
  { name: 'PE手套', spec: null, qty: null, cat: '耗材', unitPrice: null, shares: 1, note: '1盒100隻', purchaseStatus: '已購買', arrivalStatus: '已到貨', channel: '紅通通實體買' },
  { name: 'PVC管', spec: '20cm', qty: null, cat: '耗材', unitPrice: null, shares: 15, note: null, purchaseStatus: '已購買', arrivalStatus: '已到貨', channel: null },
  { name: '三用電表', spec: '鉤表', qty: 1, cat: '工具', unitPrice: null, shares: null, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: '電器材料行' },
  { name: '不銹鋼板', spec: null, qty: 8, cat: '工具', unitPrice: 95, shares: 8, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: '蝦皮' },
  { name: '不銹鋼藥勺', spec: '15cm', qty: null, cat: '非玻璃實驗器材', unitPrice: 105, shares: 2, note: '一組3隻（大中小）', purchaseStatus: '已購買', arrivalStatus: null, channel: '蝦皮' },
  { name: '乒乓球', spec: null, qty: null, cat: '耗材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '乾淨抹布', spec: null, qty: 4, cat: '工具', unitPrice: 0, shares: 6, note: null, purchaseStatus: '補習班準備', arrivalStatus: null, channel: null },
  { name: '保麗龍板', spec: '20*30*3cm', qty: null, cat: '耗材', unitPrice: null, shares: 15, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: null },
  { name: '保麗龍膠', spec: null, qty: 1, cat: '工具', unitPrice: null, shares: null, note: null, purchaseStatus: '已購買', arrivalStatus: '已到貨', channel: null },
  { name: '冰棒棍', spec: null, qty: null, cat: '耗材', unitPrice: 2, shares: 15, note: null, purchaseStatus: '已購買', arrivalStatus: '已到貨', channel: '紅通通實體買' },
  { name: '剪刀', spec: null, qty: null, cat: '文具', unitPrice: null, shares: 4, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: null },
  { name: '可彎曲吸管', spec: null, qty: null, cat: '耗材', unitPrice: null, shares: null, note: null, purchaseStatus: '已購買', arrivalStatus: '已到貨', channel: null },
  { name: '可食用海藻酸鈉', spec: '500g 全新未開封', qty: 1, cat: '粉狀藥品', unitPrice: 700, shares: 1, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: null },
  { name: '吹風機', spec: null, qty: 1, cat: '工具', unitPrice: null, shares: 1, note: null, purchaseStatus: '補習班準備', arrivalStatus: null, channel: null },
  { name: '塑膠杯', spec: '340mL', qty: null, cat: '耗材', unitPrice: null, shares: 1, note: '1條', purchaseStatus: '已購買', arrivalStatus: '已到貨', channel: '紅通通實體買' },
  { name: '塑膠滴管', spec: '3mL', qty: null, cat: '耗材', unitPrice: 170, shares: 1, note: '1包（200支）', purchaseStatus: '已購買', arrivalStatus: null, channel: '蝦皮' },
  { name: '大寶特瓶', spec: '1500mL 舒跑硬罐', qty: null, cat: '耗材', unitPrice: 38, shares: 4, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '實驗袍', spec: 'S2 M10 L4', qty: 16, cat: '安全', unitPrice: null, shares: 16, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: null },
  { name: '小夾鏈袋', spec: null, qty: null, cat: '耗材', unitPrice: null, shares: null, note: null, purchaseStatus: '已購買', arrivalStatus: '已到貨', channel: null },
  { name: '可食用乳酸鈣', spec: '500g 全新未開封', qty: 1, cat: '粉狀藥品', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '小蘇打粉', spec: '450g', qty: 1, cat: '粉狀藥品', unitPrice: 28, shares: 1, note: '1包（450g）', purchaseStatus: '已購買', arrivalStatus: null, channel: '網購' },
  { name: '帶插頭電線', spec: null, qty: 4, cat: '工具', unitPrice: null, shares: null, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: '電器材料行' },
  { name: '廚房紙巾', spec: null, qty: null, cat: '耗材', unitPrice: null, shares: 1, note: '1卷', purchaseStatus: '補習班準備', arrivalStatus: null, channel: '紅通通實體買' },
  { name: '彩色筆', spec: null, qty: null, cat: '文具', unitPrice: 51, shares: 1, note: '一組12色', purchaseStatus: null, arrivalStatus: null, channel: '蝦皮' },
  { name: '方糖', spec: '340g', qty: 1, cat: '粉狀藥品', unitPrice: null, shares: null, note: '1盒（340g）', purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '果汁飲料', spec: '250cc', qty: 4, cat: '一次性食材', unitPrice: null, shares: null, note: '老師統一購買', purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '檸檬酸粉', spec: '450g', qty: 1, cat: '粉狀藥品', unitPrice: 45, shares: null, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: '網購' },
  { name: '氣球底座', spec: '一包(100g)', qty: null, cat: '耗材', unitPrice: null, shares: 1, note: '1包（100個）', purchaseStatus: null, arrivalStatus: null, channel: '紅通通實體買' },
  { name: '氣球棒', spec: '一包(100g)', qty: null, cat: '耗材', unitPrice: null, shares: 1, note: '1包（100個）', purchaseStatus: null, arrivalStatus: null, channel: '紅通通實體買' },
  { name: '沙子', spec: '40mesh', qty: 1, cat: '粉狀藥品', unitPrice: null, shares: 1, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: '蝦皮' },
  { name: '沙拉油', spec: null, qty: null, cat: '耗材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '湯匙', spec: null, qty: null, cat: '耗材', unitPrice: null, shares: null, note: null, purchaseStatus: '已購買', arrivalStatus: '已到貨', channel: null },
  { name: '無菌滴管', spec: '全新未開封', qty: null, cat: '耗材', unitPrice: null, shares: null, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: null },
  { name: '蒸發皿', spec: '70mm (60mL)', qty: null, cat: '玻璃實驗器材', unitPrice: 69, shares: 4, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: '蝦皮' },
  { name: '熱熔膠及熱熔膠槍', spec: null, qty: 2, cat: '工具', unitPrice: 0, shares: 2, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: null },
  { name: '燒杯 100mL', spec: '100mL', qty: null, cat: '玻璃實驗器材', unitPrice: 25, shares: 4, note: null, purchaseStatus: '已購買', arrivalStatus: '已到貨', channel: '蝦皮' },
  { name: '發泡錠', spec: null, qty: 15, cat: '一次性食材', unitPrice: null, shares: null, note: '可購買市售或自製', purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '白砂糖', spec: '500g', qty: 1, cat: '粉狀藥品', unitPrice: 21, shares: 1, note: '1包（500g）', purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '盒裝牛奶', spec: '345mL 中型紙盒', qty: 4, cat: '一次性食材', unitPrice: 1, shares: 4, note: null, purchaseStatus: null, arrivalStatus: null, channel: '家樂福' },
  { name: '直立式打氣筒＋球針', spec: '160PSI', qty: 1, cat: '工具', unitPrice: 121, shares: 2, note: null, purchaseStatus: null, arrivalStatus: null, channel: '蝦皮' },
  { name: '研缽', spec: '90mm', qty: null, cat: '玻璃實驗器材', unitPrice: 100, shares: 4, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: '蝦皮' },
  { name: '竹筷', spec: '20cm', qty: null, cat: '耗材', unitPrice: null, shares: 24, note: '1包（100支）', purchaseStatus: '已購買', arrivalStatus: '已到貨', channel: '紅通通實體買' },
  { name: '竹籤', spec: '20cm', qty: null, cat: '耗材', unitPrice: null, shares: 15, note: '1包（100雙）', purchaseStatus: '已購買', arrivalStatus: '已到貨', channel: '紅通通實體買' },
  { name: '粗橡皮筋', spec: null, qty: null, cat: '耗材', unitPrice: null, shares: null, note: null, purchaseStatus: '已購買', arrivalStatus: '已到貨', channel: null },
  { name: '護目鏡', spec: null, qty: null, cat: '安全', unitPrice: null, shares: 16, note: '1人1副 一定要戴', purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '點火槍', spec: '27cm', qty: null, cat: '工具', unitPrice: null, shares: 4, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '電子秤', spec: '精度0.01g', qty: null, cat: '非玻璃實驗器材', unitPrice: null, shares: 2, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '電池盒+電線+開關', spec: '3號電池用', qty: null, cat: '耗材', unitPrice: null, shares: 15, note: '1人1個', purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '電池（3號）', spec: '3號電池', qty: null, cat: '耗材', unitPrice: null, shares: 15, note: '1人2顆', purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '鎳鉻絲', spec: '0.2mm', qty: null, cat: '耗材', unitPrice: null, shares: 15, note: '1人1條', purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '鱷魚夾', spec: '兩個一對', qty: null, cat: '工具', unitPrice: null, shares: 4, note: '1人1對', purchaseStatus: null, arrivalStatus: null, channel: null },
];
