// 實驗總表 — 所有實驗（含未來規劃）
const ALL_EXPERIMENTS = [
  { id: 'C01', title: '看不見的爆發力：黑蛇招喚術與酸鹼火箭', cat: '化學', concept: '糖熱分解碳化、小蘇打加熱/加酸產二氧化碳', format: '分組實作', duration: 100 },
  { id: 'C02', title: '星際科學實驗室：深海熔岩燈與爆漿水怪蛋', cat: '化學', concept: '油水不互溶密度差異、海藻酸鈉交聯成膜', format: '個人實作', duration: 120 },
  { id: 'P01', title: '神奇的靜電：閃電魔法杯與不插電馬達', cat: '物理', concept: '摩擦起電、感應起電、庫倫力驅動', format: '個人實作', duration: 120 },
  { id: 'P02', title: '電流與熱能的交響曲：保麗龍寶劍與電流麵包', cat: '物理', concept: '電流熱效應、電阻與能量轉換', format: '雙軌交叉進行', duration: 120 },
  { id: 'P03', title: '風的掌控者：人造雲與轉轉飛天杯', cat: '物理', concept: '白努力定律、瑪格努斯效應', format: '個人實作', duration: 100 },
  { id: null, title: '特務密碼：火焰解碼術', cat: '化學', concept: '硝酸鉀熱分解、助燃性應用', format: '個人實作', duration: 110 },
  { id: null, title: '冰雪奇緣：魔法天氣瓶', cat: '化學', concept: '樟腦結晶、溫度與溶解度', format: '個人實作', duration: 120 },
  { id: null, title: '點水成冰：急凍世界', cat: '化學', concept: '醋酸鈉過飽和溶液、結晶熱釋放', format: '個人實作', duration: 110 },
  { id: null, title: '魔法煉金術：三色變色杯', cat: '化學', concept: '氧化還原反應、酸鹼指示劑變化', format: '分組點滴板操作', duration: 90 },
  { id: null, title: '黑蛇招喚術與燃術軌跡', cat: '化學', concept: '蔗糖熱分解碳化、小蘇打受熱產氣', format: '分組實作', duration: 100 },
  { id: null, title: '大象的泡泡浴', cat: '化學', concept: '催化劑與反應速率、放熱反應', format: '分組實作', duration: 90 },
  { id: null, title: '水分子破壞者', cat: '化學', concept: '電化學、正負極氣體製備', format: '分組實作', duration: 105 },
  { id: null, title: '煉金術士的點金術', cat: '化學', concept: '氧化還原與置換、結晶型態觀察', format: '分組實作', duration: 120 },
  { id: null, title: '魔幻紅綠燈變色瓶', cat: '化學', concept: '葡萄糖氧化還原、亞甲基藍/靛胭脂', format: '個人實作', duration: 90 },
  { id: null, title: '夜光魔法與終極焰色', cat: '化學', concept: '原子光譜電子躍遷、化學發光冷光現象', format: '分組實作', duration: 100 },
  { id: '中1', title: '黑色磁力怪獸：磁力史萊姆', cat: '化學', concept: '高分子交聯作用、磁性物質感應', format: '個人實作', duration: 100 },
  { id: null, title: '尋找解藥：煉金術士矩陣', cat: '化學', concept: '離子沉澱反應、溶解度規則表格', format: '2人一組/點滴板', duration: 120 },
  { id: null, title: '時間規律者：自製時鐘', cat: '物理', concept: '古典力學、單擺等時性探究', format: '分組實作', duration: 90 },
  { id: null, title: '手動小吊車：帕斯卡契約', cat: '物理', concept: '簡單機械、槓桿原理與輪軸', format: '個人結構組裝', duration: 100 },
  { id: null, title: '天際探險：人造火箭', cat: '化學', concept: '氣體產氣壓、反作用力', format: '分組實作', duration: 90 },
];

// 器材採購清單
const MATERIALS_LIST = [
  { name: '果汁飲料', spec: '老師統一購買250cc飲料', qty: 4, cat: '一次性食材', unitPrice: null, shares: null, note: '課前購買無需儲存', purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '發泡錠', spec: '可購買市售產品或用小蘇打粉與檸檬酸自製', qty: 15, cat: '一次性食材', unitPrice: null, shares: null, note: '課前購買無需儲存', purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '盒裝牛奶', spec: '345mL 中型紙盒', qty: 4, cat: '一次性食材', unitPrice: 1, shares: 4, note: '課前購買無需儲存', purchaseStatus: null, arrivalStatus: null, channel: '家樂福' },
  { name: '鬆餅粉', spec: '500g', qty: 2, cat: '一次性食材', unitPrice: null, shares: null, note: '課前購買無需儲存', purchaseStatus: null, arrivalStatus: null, channel: '家樂福' },
  { name: '實驗袍', spec: 'S2 M10 L4', qty: 16, cat: '安全', unitPrice: null, shares: 16, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: null },
  { name: '護目鏡', spec: null, qty: null, cat: '安全', unitPrice: null, shares: 16, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: null },
  { name: '三用電表', spec: '鉤表', qty: 1, cat: '工具', unitPrice: null, shares: null, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: '電器材料行' },
  { name: '不銹鋼板', spec: null, qty: 8, cat: '工具', unitPrice: 95, shares: 8, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: 'https://shopee.tw/台灣製-304不鏽鋼版片（單面髮絲紋）多種尺寸提供選擇-不銹鋼-不鏽鋼板-白鐵片白鐵板-i.8940274.7736137116?extraParams=%7B%22display_model_id%22%3A36951046495%2C%22model_selection_logic%22%3A3%7D&sp_atk=864f66b8-6699-4ed4-9a55-d63a92cf2984&xptdk=864f66b8-6699-4ed4-9a55-d63a92cf2984' },
  { name: '乾淨抹布', spec: null, qty: 4, cat: '工具', unitPrice: 0, shares: 6, note: null, purchaseStatus: '補習班準備', arrivalStatus: null, channel: null },
  { name: '保麗龍膠', spec: null, qty: 1, cat: '工具', unitPrice: null, shares: null, note: null, purchaseStatus: '俊瑋已購買', arrivalStatus: '已到貨', channel: null },
  { name: '吹風機', spec: null, qty: 1, cat: '工具', unitPrice: null, shares: 1, note: null, purchaseStatus: '補習班準備', arrivalStatus: null, channel: null },
  { name: '帶插頭電線', spec: null, qty: 4, cat: '工具', unitPrice: null, shares: null, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: '電器材料行' },
  { name: '熱熔膠及熱熔膠槍', spec: null, qty: 2, cat: '工具', unitPrice: 0, shares: 2, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: null },
  { name: '直立式打氣筒＋球針', spec: '160PSI', qty: 1, cat: '工具', unitPrice: 121, shares: 2, note: null, purchaseStatus: null, arrivalStatus: null, channel: 'https://shopee.tw/台灣現貨🚢直立式打氣筒-豪華帶錶款-160PSI打氣筒-打氣桶-球類打氣筒-球類打氣桶-腳踏車打氣筒-自行車打氣筒-i.1224132041.46654613538?extraParams=%7B%22display_model_id%22%3A350427729105%2C%22model_selection_logic%22%3A3%7D&sp_atk=836df210-32b4-4a70-9d50-9b027af24a7a&xptdk=836df210-32b4-4a70-9d50-9b027af24a7a' },
  { name: '細頭電鑽', spec: null, qty: 1, cat: '工具', unitPrice: 0, shares: 0, note: null, purchaseStatus: '福大可借到', arrivalStatus: null, channel: null },
  { name: '美工刀', spec: null, qty: 4, cat: '工具', unitPrice: null, shares: 4, note: null, purchaseStatus: '補習班準備', arrivalStatus: null, channel: null },
  { name: '隔熱棉手套', spec: null, qty: 15, cat: '工具', unitPrice: null, shares: 24, note: null, purchaseStatus: '已購買', arrivalStatus: '已到貨', channel: '紅通通實體買' },
  { name: '電子秤', spec: '食品秤/200 (精度0.01g)', qty: 2, cat: '工具', unitPrice: 91, shares: 2, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: 'https://shopee.tw/【建昌儀器】電子秤-迷你秤-200g-500g-精度0.01克微-📌附收據📌口袋秤-珠寶秤-粉末秤-i.1253690864.25040088161?extraParams=%7B%22display_model_id%22%3A178641727834%2C%22model_selection_logic%22%3A3%7D' },
  { name: '電烙鐵套裝', spec: null, qty: 1, cat: '工具', unitPrice: 185, shares: 1, note: null, purchaseStatus: '福大可借到', arrivalStatus: null, channel: 'https://shopee.tw/【智能可調溫電烙鐵-15件全套】電烙鐵-烙鐵-焊槍-電焊槍-焊錫槍-電烙鐵套裝-電烙鐵可調溫-溫控烙鐵-60W-焊槍-i.46130292.23220684929?extraParams=%7B%22display_model_id%22%3A220818308664%2C%22model_selection_logic%22%3A3%7D' },
  { name: '靜電棒', spec: null, qty: 12, cat: '工具', unitPrice: null, shares: 15, note: null, purchaseStatus: '俊瑋已購買', arrivalStatus: null, channel: null },
  { name: '食用免洗碗', spec: '一條', qty: 1, cat: '工具', unitPrice: null, shares: null, note: null, purchaseStatus: '已購買', arrivalStatus: '已到貨', channel: '紅通通實體買' },
  { name: '鱷魚夾', spec: null, qty: 8, cat: '工具', unitPrice: null, shares: null, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: '電器材料行' },
  { name: '點火槍', spec: '27cm', qty: 4, cat: '工具', unitPrice: 30, shares: 4, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: '紅通通實體買' },
  { name: '剪刀', spec: null, qty: null, cat: '文具', unitPrice: null, shares: 4, note: null, purchaseStatus: '俊瑋已購買', arrivalStatus: null, channel: null },
  { name: '墊板', spec: null, qty: null, cat: '文具', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '彩色筆', spec: null, qty: null, cat: '文具', unitPrice: 51, shares: 1, note: null, purchaseStatus: null, arrivalStatus: null, channel: 'https://shopee.tw/SKB-彩色筆-12色-24色-36色-48色-CL-75-CL-140-CL-210-台灣製造-如需選色可在備註留言-i.165635379.6116854101?extraParams=%7B%22display_model_id%22%3A193799483583%2C%22model_selection_logic%22%3A3%7D&sp_atk=84b1d99f-c259-4a61-86cc-3c7fe932ba18&xptdk=84b1d99f-c259-4a61-86cc-3c7fe932ba18' },
  { name: '膠水', spec: null, qty: null, cat: '文具', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '色紙', spec: null, qty: null, cat: '文具', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '軟尺', spec: null, qty: null, cat: '文具', unitPrice: 1, shares: 4, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: 'https://shopee.tw/【台灣現貨⚡速發】捲尺-圓形小捲尺-迷你捲尺-馬卡龍色-捲尺-伸縮尺-量衣尺-軟尺-量尺-隨身尺-縮捲尺-皮尺-文具-i.21485454.21878754095?extraParams=%7B%22display_model_id%22%3A221500598349%2C%22model_selection_logic%22%3A3%7D&sp_atk=95d05e6a-fe6b-4628-b51a-7b05bb97c146&xptdk=95d05e6a-fe6b-4628-b51a-7b05bb97c146' },
  { name: '透明膠帶', spec: null, qty: null, cat: '文具', unitPrice: null, shares: 4, note: null, purchaseStatus: '俊瑋已購買', arrivalStatus: null, channel: null },
  { name: '酒精', spec: '95% 500mL', qty: null, cat: '液體藥品', unitPrice: null, shares: null, note: null, purchaseStatus: '俊瑋已購買', arrivalStatus: '已到貨', channel: 'https://www.meru.com.tw/products/li203092' },
  { name: '鐵氰化鉀（赤血鹽）', spec: '100g', qty: null, cat: '液體藥品', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '食用色素', spec: null, qty: null, cat: '液體藥品', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '雙氧水', spec: '500mL', qty: null, cat: '液體藥品', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '本氏液', spec: '500mL', qty: null, cat: '液體藥品', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '硫酸', spec: '98% 500mL', qty: null, cat: '液體藥品', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '甘油', spec: '500g', qty: null, cat: '液體藥品', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '酚酞指示劑', spec: '250mL', qty: null, cat: '液體藥品', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '碘液', spec: '0.1N', qty: null, cat: '液體藥品', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: 'PVA膠水', spec: '4kg', qty: null, cat: '液體藥品', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '蒸發皿', spec: '70mm (60mL)', qty: null, cat: '玻璃實驗器材', unitPrice: 69, shares: 4, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: 'https://shopee.tw/【建昌儀器】瓷蒸發皿-60-70-80-90-100-110-120-130-150mm(單面釉)-📌附收據📌-磁蒸發皿-i.1253690864.56761317429?extraParams=%7B%22display_model_id%22%3A287654584175%2C%22model_selection_logic%22%3A3%7D&sp_atk=1e9f0e13-51af-4bc1-88cd-d3db228e1dba&xptdk=1e9f0e13-51af-4bc1-88cd-d3db228e1dba' },
  { name: '燒杯', spec: '50mL', qty: null, cat: '玻璃實驗器材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '燒杯', spec: '100mL', qty: null, cat: '玻璃實驗器材', unitPrice: 25, shares: 4, note: null, purchaseStatus: '俊瑋已購買', arrivalStatus: '已到貨', channel: 'https://shopee.tw/玻璃燒杯-立聖實驗器材-低型玻璃燒杯-10ml~1000ml-實驗燒杯-刻度量杯-i.6433712.30539335?extraParams=%7B%22display_model_id%22%3A221688904706%2C%22model_selection_logic%22%3A3%7D' },
  { name: '燒杯', spec: '250mL', qty: null, cat: '玻璃實驗器材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '燒杯', spec: '500mL', qty: null, cat: '玻璃實驗器材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '研缽', spec: '90mm', qty: null, cat: '玻璃實驗器材', unitPrice: 100, shares: 4, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: 'https://shopee.tw/現貨-陶瓷研缽組-研缽-杵-臺製-90mm-120mm-研砵-台製研砵-高品質研砵-i.477364706.18666357314?extraParams=%7B%22display_model_id%22%3A175254158585%2C%22model_selection_logic%22%3A3%7D&sp_atk=207018e5-6d15-4848-93b0-c636a0c0769b&xptdk=207018e5-6d15-4848-93b0-c636a0c0769b' },
  { name: '量筒', spec: null, qty: null, cat: '玻璃實驗器材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '吸量管', spec: null, qty: null, cat: '玻璃實驗器材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '培養皿', spec: null, qty: null, cat: '玻璃實驗器材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '漏斗', spec: null, qty: null, cat: '玻璃實驗器材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '玻璃攪拌棒', spec: null, qty: null, cat: '玻璃實驗器材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '錐形瓶', spec: null, qty: null, cat: '玻璃實驗器材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '吸濾瓶', spec: null, qty: null, cat: '玻璃實驗器材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '試管', spec: null, qty: null, cat: '玻璃實驗器材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '萃取瓶', spec: null, qty: null, cat: '玻璃實驗器材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '玻璃滴管', spec: null, qty: null, cat: '玻璃實驗器材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '溫度計', spec: null, qty: null, cat: '玻璃實驗器材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '酒精燈', spec: null, qty: null, cat: '玻璃實驗器材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '容量瓶', spec: null, qty: null, cat: '玻璃實驗器材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '錐形瓶', spec: null, qty: null, cat: '玻璃實驗器材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '既頭漏斗', spec: null, qty: null, cat: '玻璃實驗器材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '冷凝管', spec: null, qty: null, cat: '玻璃實驗器材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '血清瓶', spec: null, qty: null, cat: '玻璃實驗器材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '滴定管', spec: null, qty: null, cat: '玻璃實驗器材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '雷射水平光', spec: null, qty: null, cat: '玻璃實驗器材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '透鏡玻璃', spec: null, qty: null, cat: '玻璃實驗器材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '可食用海藻酸鈉', spec: '500g 全新未開封', qty: 1, cat: '粉狀藥品', unitPrice: 700, shares: 1, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: null },
  { name: '可食用乳酸鈣', spec: '500g 全新未開封', qty: 1, cat: '粉狀藥品', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '小蘇打粉', spec: '450g', qty: 1, cat: '粉狀藥品', unitPrice: 28, shares: 1, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: 'https://www.meru.com.tw/products/si300051' },
  { name: '方糖', spec: '340g', qty: 1, cat: '粉狀藥品', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: 'https://online.uni-prosperity.com.tw/zh/1437006400101.html' },
  { name: '檸檬酸粉', spec: '450g', qty: 1, cat: '粉狀藥品', unitPrice: 45, shares: null, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: 'https://www.meru.com.tw/products/sf300367?gad_source=1&utm_medium=shopping_ads&utm_source=google' },
  { name: '沙子', spec: '40mesh (約0.05~0.1cm)', qty: 1, cat: '粉狀藥品', unitPrice: null, shares: 1, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: 'https://shopee.tw/【欣榮二館免運快速出貨】白細沙-沙坑-白細砂-白沙-遊戲沙-遊戲砂-海灘沙-石英砂-i.1186936762.41755430785?extraParams=%7B%22display_model_id%22%3A305457984550%2C%22model_selection_logic%22%3A3%7D&sp_atk=76f1313e-155a-4533-ba73-13c0dd479b63&xptdk=76f1313e-155a-4533-ba73-13c0dd479b63' },
  { name: '白砂糖', spec: '500g', qty: 1, cat: '粉狀藥品', unitPrice: 21, shares: 1, note: null, purchaseStatus: null, arrivalStatus: null, channel: 'https://online.uni-prosperity.com.tw/zh/台糖/1437007600101.html' },
  { name: '紅砂糖', spec: '400g', qty: 1, cat: '粉狀藥品', unitPrice: 18, shares: 1, note: null, purchaseStatus: null, arrivalStatus: null, channel: 'https://online.uni-prosperity.com.tw/zh/台糖/1437002000101.html' },
  { name: '非食用海藻酸鈉', spec: '450g', qty: 2, cat: '粉狀藥品', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '氫氧化鈉', spec: '500g', qty: null, cat: '粉狀藥品', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '硼砂', spec: '500g', qty: null, cat: '粉狀藥品', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '鐵粉', spec: null, qty: null, cat: '粉狀藥品', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '鎂粉', spec: null, qty: null, cat: '粉狀藥品', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '鎂帶', spec: '25g', qty: null, cat: '粉狀藥品', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '鋅粉', spec: '1kg', qty: null, cat: '粉狀藥品', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '葡萄糖', spec: '450g', qty: null, cat: '粉狀藥品', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '硝酸鉛', spec: '500g', qty: null, cat: '粉狀藥品', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '氯化鈣', spec: '500g', qty: null, cat: '粉狀藥品', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '酚酞粉末', spec: '25g', qty: null, cat: '粉狀藥品', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '魯米諾', spec: '5g', qty: null, cat: '粉狀藥品', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '靛藍胭脂紅', spec: '25g', qty: null, cat: '粉狀藥品', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '碘化鉀', spec: '100g', qty: null, cat: '粉狀藥品', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: 'PE手套', spec: null, qty: null, cat: '耗材', unitPrice: null, shares: 1, note: null, purchaseStatus: '俊瑋已購買', arrivalStatus: '已到貨', channel: '紅通通實體買' },
  { name: 'PVC管', spec: '20cm', qty: null, cat: '耗材', unitPrice: null, shares: 15, note: null, purchaseStatus: '俊瑋已購買', arrivalStatus: '已到貨', channel: null },
  { name: '乒乓球', spec: null, qty: null, cat: '耗材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '保麗龍板', spec: '20*30*3cm', qty: null, cat: '耗材', unitPrice: null, shares: 15, note: null, purchaseStatus: '俊瑋已購買', arrivalStatus: null, channel: null },
  { name: '冰棒棍', spec: null, qty: null, cat: '耗材', unitPrice: 2, shares: 15, note: null, purchaseStatus: '已購買', arrivalStatus: '已到貨', channel: '紅通通實體買' },
  { name: '可彎曲吸管', spec: null, qty: null, cat: '耗材', unitPrice: null, shares: null, note: null, purchaseStatus: '俊瑋已購買', arrivalStatus: '已到貨', channel: null },
  { name: '塑膠杯', spec: '340mL', qty: null, cat: '耗材', unitPrice: null, shares: 1, note: null, purchaseStatus: '俊瑋已購買', arrivalStatus: '已到貨', channel: '紅通通實體買' },
  { name: '塑膠滴管', spec: '3mL', qty: null, cat: '耗材', unitPrice: 170, shares: 1, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: 'https://shopee.tw/立聖實驗器材-塑膠滴管-拋棄式滴管-PP量管-塑膠吸管-i.6433712.40488790?extraParams=%7B%22display_model_id%22%3A23442646%2C%22model_selection_logic%22%3A3%7D&sp_atk=f8e0e51c-64ee-413a-be9e-9e5c012e9e1d&xptdk=f8e0e51c-64ee-413a-be9e-9e5c012e9e1d' },
  { name: '大寶特瓶子', spec: '1500mL 舒跑硬罐', qty: null, cat: '耗材', unitPrice: 38, shares: 4, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '小夾鏈袋', spec: null, qty: null, cat: '耗材', unitPrice: null, shares: null, note: null, purchaseStatus: '俊瑋已購買', arrivalStatus: '已到貨', channel: null },
  { name: '廚房紙巾', spec: null, qty: null, cat: '耗材', unitPrice: null, shares: 1, note: null, purchaseStatus: '補習班準備', arrivalStatus: null, channel: '紅通通實體買' },
  { name: '氣球底座', spec: '一包(100g)', qty: null, cat: '耗材', unitPrice: null, shares: 1, note: null, purchaseStatus: null, arrivalStatus: null, channel: '紅通通實體買' },
  { name: '氣球棒', spec: '一包(100g)', qty: null, cat: '耗材', unitPrice: null, shares: 1, note: null, purchaseStatus: null, arrivalStatus: null, channel: '紅通通實體買' },
  { name: '沙拉油', spec: null, qty: null, cat: '耗材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '湯匙', spec: null, qty: null, cat: '耗材', unitPrice: null, shares: null, note: null, purchaseStatus: '已購買', arrivalStatus: '已到貨', channel: null },
  { name: '滴管', spec: null, qty: null, cat: '耗材', unitPrice: 1, shares: null, note: null, purchaseStatus: '俊瑋已購買', arrivalStatus: '已到貨', channel: null },
  { name: '無菌滴管', spec: '全新未開封', qty: null, cat: '耗材', unitPrice: null, shares: null, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: null },
  { name: '竹筷', spec: '20cm', qty: null, cat: '耗材', unitPrice: null, shares: 24, note: null, purchaseStatus: '俊瑋已購買', arrivalStatus: '已到貨', channel: '紅通通實體買' },
  { name: '竹籤', spec: '20cm', qty: null, cat: '耗材', unitPrice: null, shares: 15, note: null, purchaseStatus: '俊瑋已購買', arrivalStatus: '已到貨', channel: '紅通通實體買' },
  { name: '粗橡皮筋', spec: null, qty: null, cat: '耗材', unitPrice: null, shares: null, note: null, purchaseStatus: '已購買', arrivalStatus: '已到貨', channel: null },
  { name: '紙杯', spec: null, qty: null, cat: '耗材', unitPrice: null, shares: null, note: null, purchaseStatus: '俊瑋已購買', arrivalStatus: '已到貨', channel: null },
  { name: '線香', spec: null, qty: null, cat: '耗材', unitPrice: 5, shares: 4, note: null, purchaseStatus: '俊瑋已購買', arrivalStatus: '已到貨', channel: '紅通通實體買' },
  { name: '胖胖寶特瓶', spec: '345mL', qty: null, cat: '耗材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '衛生紙', spec: null, qty: null, cat: '耗材', unitPrice: null, shares: 1, note: null, purchaseStatus: '補習班準備', arrivalStatus: null, channel: '紅通通實體買' },
  { name: '軟木塞', spec: '#14 20*25', qty: null, cat: '耗材', unitPrice: 19, shares: 8, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: null },
  { name: '透明膠帶', spec: '18mm', qty: null, cat: '耗材', unitPrice: null, shares: 3, note: null, purchaseStatus: '俊瑋已購買', arrivalStatus: '已到貨', channel: '紅通通實體買' },
  { name: '鋁箔紙', spec: null, qty: null, cat: '耗材', unitPrice: null, shares: 2, note: null, purchaseStatus: '俊瑋已購買', arrivalStatus: '已到貨', channel: '紅通通實體買' },
  { name: '鎳鉻絲', spec: '0.2mm', qty: null, cat: '耗材', unitPrice: 85, shares: 1, note: null, purchaseStatus: null, arrivalStatus: null, channel: 'https://shopee.tw/Ni80-Nichrome-保麗龍切割線-封口機加熱線-發熱絲-電熱線-i.709421498.14363573584?extraParams=%7B%22display_model_id%22%3A134726580476%2C%22model_selection_logic%22%3A3%7D&sp_atk=c603f15e-21a6-4482-a2c6-a73b46264a9c&xptdk=c603f15e-21a6-4482-a2c6-a73b46264a9c' },
  { name: '電氣膠帶PVC', spec: '18mm', qty: null, cat: '耗材', unitPrice: null, shares: 3, note: null, purchaseStatus: '俊瑋已購買', arrivalStatus: '已到貨', channel: '紅通通實體買' },
  { name: '電池', spec: null, qty: null, cat: '耗材', unitPrice: null, shares: 15, note: null, purchaseStatus: null, arrivalStatus: null, channel: '紅通通實體買' },
  { name: '電池盒+電線+開關', spec: '含電線', qty: null, cat: '耗材', unitPrice: 59, shares: 15, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: 'https://shopee.tw/18650電池盒｜串聯-並聯可選｜帶線-帶蓋-開關｜DIY供電模組-i.147993740.12313475007?extraParams=%7B%22display_model_id%22%3A310858791379%2C%22model_selection_logic%22%3A3%7D&sp_atk=52442b54-0f9e-499e-9f57-b3d1ec9633e3&xptdk=52442b54-0f9e-499e-9f57-b3d1ec9633e3' },
  { name: '不銹鋼藥勺', spec: '15cm', qty: null, cat: '非玻璃實驗器材', unitPrice: 105, shares: 2, note: null, purchaseStatus: '已購買', arrivalStatus: null, channel: 'https://shopee.tw/台製-不銹鋼藥匙-Spoons-秤藥匙-秤量匙-不鏽鋼秤量匙-三支組藥匙-i.477364706.21337508760?extraParams=%7B%22display_model_id%22%3A191915855151%2C%22model_selection_logic%22%3A3%7D' },
  { name: '大量杯', spec: '1500mL/2000mL', qty: null, cat: '非玻璃實驗器材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '安全吸球', spec: null, qty: null, cat: '非玻璃實驗器材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '鑷子', spec: null, qty: null, cat: '非玻璃實驗器材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '濾紙', spec: null, qty: null, cat: '非玻璃實驗器材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '三腳架', spec: null, qty: null, cat: '非玻璃實驗器材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '陶瓷纖維網', spec: null, qty: null, cat: '非玻璃實驗器材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '分子結構球棍模型組', spec: null, qty: null, cat: '非玻璃實驗器材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '電子顯微鏡', spec: null, qty: null, cat: '非玻璃實驗器材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
  { name: '光學顯微鏡', spec: null, qty: null, cat: '非玻璃實驗器材', unitPrice: null, shares: null, note: null, purchaseStatus: null, arrivalStatus: null, channel: null },
];